version: '3'

volumes:
  postgresql_data:

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${GREENLIGHT_DB_NAME}
      POSTGRES_USER: ${GREENLIGHT_DB_USER}
      POSTGRES_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
